api_app/urls.py
from django.urls import path
from .views import JogadorList, Objeto_erList, Objeto_er_mapList, personagens_proximos, me, mochila, job_check_online_users

# *************************************************
from rest_framework import routers

router = routers.DefaultRouter()
router.register('jogador', JogadorList, 'jogador')
router.register('objeto_er', Objeto_erList, 'objeto_er')
router.register('objeto_er_map', Objeto_er_mapList, 'objeto_er_map')

urlpatterns = router.urls
# *************************************************


app_name = "api_app"
urlpatterns += [
    path('personagens/', personagens_proximos, name='personagens_proximos'),
    path('me/', me, name='me'),
    path('mochila/', mochila, name='mochila'),
    path(
        'job_check_online_users/',
        job_check_online_users,
        name='job_check_online_users')
]

core_app/urls.py
from django.urls import path, include, reverse_lazy
from .views import singup_json, singup
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as auth_token
from rest_framework import routers

router = routers.DefaultRouter()

app_name = "core_app"
urlpatterns = [
    path('login/json/', auth_token.obtain_auth_token, name='login_json'),
    path('login/', auth_views.LoginView.as_view(template_name="core_app/login.html",
                                                redirect_authenticated_user=True), name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name="core_app/logout.html"),
        name='logout'),
    path('singup/json/', singup_json, name='singup_json'),
    path('singup/', singup, name='singup'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name="core_app/password_change_form.html",
             success_url=reverse_lazy('core_app:password_change_done')
         ), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="core_app/password_change_done.html"
         ), name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="core_app/password_reset_form.html",
             email_template_name="core_app/password_reset_email.html",
             success_url=reverse_lazy('core_app:password_reset_done')
         ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="core_app/password_reset_done.html"
         ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="core_app/password_reset_confirm.html",
             success_url=reverse_lazy('core_app:password_reset_complete')
         ), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="core_app/password_reset_complete.html"),
         name='password_reset_complete'
         ),
    path('api/', include((router.urls, 'api'), namespace=None)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

khunters/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api_app.urls')),
    path('', include('website_app.urls')),
    path('', include('core_app.urls')),
]

website_app/urls.py
from django.urls import path
from website_app import views

app_name = "website_app"
urlpatterns = [
    path('', views.index, name='Index'),
    path('jogadores/', views.Jogadores, name='Jogadores'),

    path(
        'jogadores/add/',
        views.JogadorCreate.as_view(),
        name='Add_Jogador'),

    path(
        'jogadores/up/<int:pk>/',
        views.JogadorUpdateView.as_view(),
        name='Update_Jogador'),

    path(
        'jogadores/del/<int:pk>/',
        views.JogadorDeleteView.as_view(),
        name='Delete_Jogador'),

    path(
        'objeto_ers/',
        views.Objeto_ers,
        name='Objeto_ers'),

    path(
        'objeto_ers/add/',
        views.Objeto_erCreate.as_view(),
        name='Add_Objeto_er'),

    path(
        'objeto_ers/up/<int:pk>/',
        views.Objeto_erUpdateView.as_view(),
        name='Update_Objeto_er'),

    path(
        'objeto_ers/del/<int:pk>/',
        views.Objeto_erDeleteView.as_view(),
        name='Delete_Objeto_er'),

    path(
        'objeto_er_maps/',
        views.Objeto_er_maps,
        name='Objeto_er_maps'),

    path(
        'objeto_er_maps/add/',
        views.Objeto_er_mapCreate.as_view(),
        name='Add_Objeto_er_map'),

    path(
        'objeto_er_maps/up/<int:pk>/',
        views.Objeto_er_mapUpdateView.as_view(),
        name='Update_Objeto_er_map'),

    path(
        'objeto_er_maps/del/<int:pk>/',
        views.Objeto_er_mapDeleteView.as_view(),
        name='Delete_Objeto_er_map'),
]

website_app/models.py
from .models_includes import NIVEL_DE_AUTISMO, AREA_DE_CONHECIMENTO, DIFICULDADE, TIPO_DE_ARQUIVO, IDIOMA
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from storages.backends.ftp import FTPStorage
SERVIDOR_FTP_WEB = FTPStorage()


class Jogador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=255, null=True, blank=True)
    online = models.BooleanField(default=False)
    latitude = models.CharField(
        'Latitude', max_length=255, null=True, blank=True)
    longitude = models.CharField(
        'Longitude', max_length=255, null=True, blank=True)
    animacao = models.CharField(max_length=255, null=True, blank=True)
    nivel_de_autismo = models.CharField(
        'Nível de Autismo', choices=NIVEL_DE_AUTISMO, max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('website_app:Jogadores')


@receiver(post_save, sender=User)
def save_user_jogador(sender, instance, **kwargs):
    Jogador.objects.get_or_create(user=instance)


class Personagem(models.Model):
    descricao = models.CharField("Descrição", max_length=100)
    prefab = models.CharField(max_length=50)
    tamanho = models.CharField("Tamanho: ", max_length=10, default="1.0")

    def __str__(self):
        return str(self.descricao)

    class Meta:
        ordering = ('descricao',)


class Objeto_er(models.Model):
    personagem = models.ForeignKey(
        Personagem, on_delete=models.PROTECT, null=True, blank=True)
    titulo = models.CharField(
        'Titulo do objeto de aprendizagem', max_length=255, null=True, blank=True)
    sub_titulo = models.CharField(
        'Sub titulo', max_length=255, null=True, blank=True)
    descricao = models.CharField(
        'Descrição', max_length=255, null=True, blank=True)
    area_de_conhecimento = models.CharField(
        'Área de Conhecimento', choices=AREA_DE_CONHECIMENTO, max_length=50, null=True, blank=True)
    dificuldade = models.CharField(
        'Nível de dificuldade', choices=DIFICULDADE, max_length=20, null=True, blank=True)
    tipo_de_arquivo = models.CharField(
        'Tipo de arquivo', max_length=10, choices=TIPO_DE_ARQUIVO, null=True, blank=True)
    # Text
    autor = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, blank=True)
    texto = models.CharField('Texto', max_length=255, null=True, blank=True)
    idioma = models.CharField('Idioma', max_length=10,
                              choices=IDIOMA, null=True, blank=True)
    # Imagem
    arquivo_1 = models.FileField(
        'Arquivo Principal', upload_to='arquivos/objeto_er/', null=True, blank=True, storage=SERVIDOR_FTP_WEB)
    arquivo_2 = models.FileField(
        'Arquivo Secundário:', upload_to='arquivos/objeto_er/', null=True, blank=True, storage=SERVIDOR_FTP_WEB)
    # Audio, Video
    duracao = models.IntegerField(
        "Duração em Minutos", default=0, null=True, blank=True)

    def __str__(self):
        return str(self.personagem) + " - " + str(self.titulo)

    def get_absolute_url(self):
        return reverse('website_app:Objeto_ers')


class Objeto_er_map(models.Model):
    latitude = models.CharField(
        'Latitude', max_length=255, null=True, blank=True)
    longitude = models.CharField(
        'Longitude', max_length=255, null=True, blank=True)
    objeto_er = models.ForeignKey(Objeto_er, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.objeto_er)

    def get_absolute_url(self):
        return reverse('website_app:Objeto_er_maps')


class Captura(models.Model):
    latitude = models.CharField(max_length=255, null=True, blank=True)
    longitude = models.CharField(max_length=255, null=True, blank=True)
    objeto_er = models.ForeignKey(Objeto_er, on_delete=models.CASCADE)
    data = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.objeto_er)

    def get_absolute_url(self):
        return reverse('website_app:index')


class Mochila(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    personagem = models.ForeignKey(
        Personagem, on_delete=models.PROTECT, null=True, blank=True)
    quantidade = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return str(self.user) + ' - ' + str(self.personagem)

website_app/views.py
from django.shortcuts import render
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from .models import Personagem, Objeto_er, Objeto_er_map, Jogador
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test


def index(request):
    contexto = {}
    Personagem.objects.get_or_create(
        descricao="Moeda Dourada", prefab="MoedaDourada")
    Objeto_er.objects.get_or_create(personagem=Personagem.objects.first())
    return render(request, 'website_app/index.html', contexto)


def login_staff_required(function=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_staff,
        login_url="/",
        redirect_field_name=None
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


def Jogadores(request):
    jogadores = Jogador.objects.all()
    lista = []
    for i in jogadores:
        try:
            lista.append([float(i.longitude.replace(',', '.')),
                          float(i.latitude.replace(',', '.'))])
        except BaseException:
            pass
    contexto = {
        "jogadores": Jogador.objects.all(),
        "lista_js": lista
    }
    return render(request, 'website_app/jogadores.html', contexto)


class JogadorCreate(CreateView):
    model = Jogador
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


class JogadorUpdateView(UpdateView):
    model = Jogador
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


class JogadorDeleteView(DeleteView):
    model = Jogador
    success_url = reverse_lazy('website_app:Jogadores')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


def Objeto_ers(request):
    contexto = {
        "lista": Objeto_er.objects.all(),
    }
    contexto["item_active_objeto_er"] = "active"
    return render(request, 'website_app/objeto_ers.html', contexto)


class Objeto_erCreate(CreateView):
    model = Objeto_er
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


class Objeto_erUpdateView(UpdateView):
    model = Objeto_er
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


class Objeto_erDeleteView(DeleteView):
    model = Objeto_er
    success_url = reverse_lazy('website_app:Objeto_ers')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


# ---------- Objeto_er_maps ---------------------------------------------------


def Objeto_er_maps(request):
    objeto_er_maps = Objeto_er_map.objects.all()
    lista = []
    for i in objeto_er_maps:
        lista.append(
            [
                float(i.longitude.replace(',', '.')),
                float(i.latitude.replace(',', '.'))
            ]
        )
    contexto = {
        "lista": Objeto_er_map.objects.all(),
        "lista_js": lista
    }
    contexto["item_active_objeto_er_map"] = "active"
    # return HttpResponse(lista)
    return render(request, 'website_app/objeto_er_maps.html', contexto)


class Objeto_er_mapCreate(CreateView):
    model = Objeto_er_map
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context


class Objeto_er_mapUpdateView(UpdateView):
    model = Objeto_er_map
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context


class Objeto_er_mapDeleteView(DeleteView):
    model = Objeto_er_map
    success_url = reverse_lazy('website_app:Objeto_er_maps')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context

website_app/templates/website_app/confirm_delete.html
{% extends "website_app/includes/base.html" %}
{% block content %}
<div class="ui container text left aligned" style="margin-top:2em;margin-bottom:10em;" >
  <form action="" class="ui text container" style="text-align: center;margin-top: 2em;" method="post">{% csrf_token %}
    <p>Tem certeza que Deseja Excluir <b>{{ object }}</b> ?</p>
    <button type="submit" class="red ui button" >Confirmar</button>
  </form>
</div>
{% endblock %}

website_app/templates/website_app/form.html
{% extends "website_app/includes/base.html" %}
{% block content %}
<div class="ui container text" style="min-height:20em">
  {%if item_active_objeto_er_map %}
  <!-- Inicio mapa -->
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
  <div id='map' style="width: 100% !important;height: 25em !important;margin-bottom: 2em;"></div>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoibmF5bHNvbmZzYSIsImEiOiJjanp2dGd0eXowMW4xM2hsZ2pkaHowdWtkIn0.wBsVgEtB34qVagCHzalIQg';
    var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-37.323209, -5.206060], // starting position
      zoom: 13 // starting zoom
    });
    var ponto = new mapboxgl.Marker().setLngLat([-37.323209, -5.206060]).addTo(map);
    map.on('click', function (e) {
      ponto.setLngLat(e.lngLat);
      map.setCenter(e.lngLat);
      $("#id_latitude").val(e.lngLat.lat);
      $("#id_longitude").val(e.lngLat.lng);
    });
    $(document).ready(function () {
      ponto.setLngLat([$("#id_longitude").val(), $("#id_latitude").val()]);
      map.setCenter([$("#id_longitude").val(), $("#id_latitude").val()]);
    });
  </script>
  <!-- Fim mapa -->
  {%endif%}
  <form class="ui form formulario " method="post" enctype="multipart/form-data">{% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.mensagem }}
    {% for field in form %}
    <div class="field">
      <label>{{ field.label_tag }} {{ field.errors }}</label>
      {{ field }}
    </div>
    {% endfor %}

    <input type="hidden" name="autor" value="{{request.user.pk}}" style="display:none" />
    <p></p>
    <button class="ui button fluid blue" type="submit">Salvar</button>
  </form>

</div>

{% endblock %}

website_app/templates/website_app/index.html
<!DOCTYPE html>
<html>

<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <!-- <meta http-equiv="refresh" content="5"> -->
  {% load static %}
  {% include 'website_app/includes/cabecalho.html' %}
</head>

<body>
  {% include 'website_app/includes/menus.html' %}
  <!-- Page Contents -->
  <div class="pusher">
    {% include 'website_app/includes/menu_horizontal.html' %}
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="column">
          <h2>
            <a class="ui header"
              href="https://ppgcc.ufersa.edu.br/wp-content/uploads/sites/42/2018/08/Dissertac%CC%A7a%CC%83o-K-Hunters-Vers%C3%A3o-Final.pdf">
              Knowledgemon Hunters: Um jogo sério com geolocalização
              para apoiar a aprendizagem de crianças com autismo e
              dificuldades de aprendizado
            </a>
          </h2>
          <p>
            O KHunters é um jogo sério voltado para minimização do tempo de isolamento social e
            para o auxílio na aprendizagem de crianças com Transtorno do Espectro Autista (TEA).
            Através de um dispositivo móvel, as crianças podem encontrar monstros virtuais 3D,
            que estão geograficamente espalhados pelo mundo e, a partir de sua captura e interação,
            visualizar os conteúdos que estes oferecem. Além disso, o jogo também permite a
            interação com os conteúdos e monstros através de Realidade Virtual e Realidade
            Aumentada, para que o usuário sinta-se motivado a utilizar a aplicação. O jogo é
            desenvolvido e mantido através da parceria entre a Universidade Federal Rural do Semi-
            Árido (UFERSA) e a Unidade de Ensino Superior Dom Bosco (UNDB).
          </p>
          <h3 class="ui header">O JOGO</h3>
          <p>
            O jogo K-Hunters, é voltado para plataformas móveis que possuem hardware de GPS e que detém o sistema
            operacional Android 3. A partir destes dispositivos, o jogo pode ser executado e permitir que as crianças
            busquem os monstros virtuais. O jogo provê um ambiente tridimensional de busca e visualização de monstros
            virtuais detentores de conhecimento. A aplicação pode ser executada em plataformas móveis que possuem
            hardware de GPS (Global Position System). A Figura 2 ilustra como a matriz de planos, o posicionamento do
            avatar e a interface principal do jogo são organizados
          </p>
        </div>
      </div>
      <div class="row">
        <div class="center aligned column">
          <!--  -->
        </div>
      </div>
    </div>
    {% include 'website_app/includes/rodape.html' %}
  </div>

</body>

</html>

website_app/templates/website_app/jogadores.html
{% extends "website_app/includes/base.html" %}
{% block content %}
<div class="ui container">
  <!-- Inicio mapa -->
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
  <div id='map' style="width: 100% !important;height: 30em !important;"></div>
  <script>
    mapboxgl.accessToken =
      'pk.eyJ1IjoibmF5bHNvbmZzYSIsImEiOiJjanp2dGd0eXowMW4xM2hsZ2pkaHowdWtkIn0.wBsVgEtB34qVagCHzalIQg';
    var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-37.323209, -5.206060], // starting position
      zoom: 4 // starting zoom
    });
    // var ponto = new mapboxgl.Marker({color:"#E8310A"}).setLngLat([-37.323209, -5.206060]).addTo(map);
    var lista_pontos = {{lista_js}}; // Interpolador Django
    console.log(lista_pontos)
    $(document).ready(function() {
      lista_pontos.forEach(element => {
        new mapboxgl.Marker().setLngLat(element).addTo(map);
      });

      $(".jogador").on("click", function(e) {
        // console.log(e.target.dataset.lng); .Marker({color:"#E8310A"})
        //ponto.setLngLat([e.target.dataset.lng,e.target.dataset.lat]);
        map.setCenter([e.target.dataset.lng, e.target.dataset.lat]);
        map.setZoom(18);
      })
    });
  </script>
  <!-- Fim mapa -->

  <a href="{% url 'website_app:Add_Jogador'%}" class="ui button blue">Cadastrar</a>
  <table class="ui single line table">
    <thead>
      <tr>
        <th>User</th>
        <th>Idade</th>
        <th>Status</th>
        <th>Localização</th>
        <th>Nível de Autismo</th>
        <th class="center aligned">Editar</th>
      </tr>
    </thead>
    <tbody>
      {% for item in jogadores %}
      <tr>
        <td>{{item.user.profile.nome|default:item.user}}</td>
        <td>{{item.user.profile.idade}} Anos</td>
        <td>
          {% if item.online %}
          Online
          {% else %}
          Offline
          {% endif %}
        </td>
        <td>
          {% if item.latitude %}
          <a class="jogador" href="#" data-lng="{{item.longitude}}"
            data-lat="{{item.latitude}}">{{item.latitude}}<br />{{item.longitude}}</a>
          {% endif %}
        </td>
        <td>{{ item.get_nivel_de_autismo_display|default:"Não classificado" }}</td>
        <td class="center aligned">
          <a href="" class="ui button blue">Editar</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

website_app/templates/website_app/login.html
{% load i18n static %}

<!DOCTYPE html>
<html>

<head>
  {% load static %}
  {% include 'website_app/includes/cabecalho.html' %}
</head>

<body>
  {% block content %}
  {% if form.errors and not form.non_field_errors %}
  <p class="ui label">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
  </p>
  {% endif %}

  {% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
  <p class="ui label">
    {{ error }}
  </p>
  {% endfor %}
  {% endif %}

  <div class="ui raised very padded text container segment" style="margin-top:2em">
    <img class="ui image fluid" src="http://les.ufersa.edu.br/khunters/icons/LogoGrande.png" alt="Logo">
    <form action="" method="post" class="ui form">{% csrf_token %}
      <div class="field">
        {{ form.username.errors }}
        {{ form.username.label_tag }} {{ form.username }}
      </div>
      <div class="field">
        {{ form.password.errors }}
        {{ form.password.label_tag }} {{ form.password }}
      </div>
      <div class="field">
        <label>&nbsp;</label><button class="ui button positive" type="submit">{% trans 'Log in' %}</button>
      </div>
    </form>
  </div>
  {% endblock %}
</body>

</html>

website_app/templates/website_app/logout.html
{% load i18n static %}
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    {% include 'website_app/includes/cabecalho.html' %}
</head>

<body>
    {% block content %}
    <div class="ui text container  center aligned" style="margin-top:2em">
        <p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

        <p><a href="{% url 'website_app:Login' %}">{% trans 'Log in again' %}</a></p>
    </div>
    {% endblock %}

</body>

</html>

website_app/templates/website_app/objeto_er_maps.html
{% extends "website_app/includes/base.html" %}
{% block content %}
<div class="ui container">
  <!-- Inicio mapa -->
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
  <div id='map' style="width: 100% !important;height: 30em !important;"></div>
  <script>
    mapboxgl.accessToken = 'pk.eyJ1IjoibmF5bHNvbmZzYSIsImEiOiJjanp2dGd0eXowMW4xM2hsZ2pkaHowdWtkIn0.wBsVgEtB34qVagCHzalIQg';
    var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'mapbox://styles/mapbox/streets-v11',
      center: [-37.323209, -5.206060], // starting position
      zoom: 13 // starting zoom
    });
    // var ponto = new mapboxgl.Marker({color:"#E8310A"}).setLngLat([-37.323209, -5.206060]).addTo(map);
    var lista_pontos = {{lista_js}}; // Interpolador Django
    
    $(document).ready(function(){
      lista_pontos.forEach(element => {
      new mapboxgl.Marker().setLngLat(element).addTo(map);
    });
      $(".objeto_er_map").on("click",function(e){
        // console.log(e.target.dataset.lng); .Marker({color:"#E8310A"})
        //ponto.setLngLat([e.target.dataset.lng,e.target.dataset.lat]);
        map.setCenter([e.target.dataset.lng,e.target.dataset.lat]);
        map.setZoom(18);
      })
    });
  </script>
  <!-- Fim mapa -->
  <a href="{% url 'website_app:Add_Objeto_er_map'%}" class="ui button blue">Cadastrar</a>
  <table class="ui single line table">
    <thead>
      <tr>
        <th>Objeto de aprendizagem</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th class="center aligned">Editar</th>
        <th class="center aligned">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for item in lista %}
      <tr>
        <td>
          <a href="#" class="objeto_er_map" data-lng="{{item.longitude}}" data-lat="{{item.latitude}}">
            {{item.objeto_er.get_tipo_de_objeto_display}} {{item.objeto_er}}
          </a>
        </td>
        <td>{{item.latitude}}</td>
        <td>{{item.longitude}}</td>
        <td class="center aligned"><a href="{% url 'website_app:Update_Objeto_er_map' item.pk %}"
            class="ui button blue">Editar</a></td>
        <td class="center aligned"><a href="{% url 'website_app:Delete_Objeto_er_map' item.pk %}"
            class="ui button red">Excluir</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

website_app/templates/website_app/objeto_ers.html
{% extends "website_app/includes/base.html" %}
{% block content %}
<div class="ui container">
  <a href="{% url 'website_app:Add_Objeto_er'%}" class="ui button blue">Cadastrar</a>
  <table class="ui single line table">
    <thead>
      <tr>
        <th>Personagem</th>
        <th>Titulo</th>
        <th>Sub titulo</th>
        <th>Descrição</th>
        <th>Área de Conhecimento</th>
        <th>Nível de dificuldade</th>
        <th>Autor</th>
        <th class="center aligned">Editar</th>
        <th class="center aligned">Excluir</th>
      </tr>
    </thead>
    <tbody>
      {% for item in lista %}
      <tr>
        <td>{{item.personagem}}</td>
        <td>{{item.titulo}}</td>
        <td>{{item.sub_titulo}}</td>
        <td>{{item.descricao}}</td>
        <td>{{ item.get_area_de_conhecimento_display }}</td>
        <td>{{ item.get_dificuldade_display }}</td>
        <td>{{ item.autor.profile.email }}</td>
        <td class="center aligned"><a href="{% url 'website_app:Update_Objeto_er' item.pk %}"
            class="ui button blue">Editar</a></td>
        <td class="center aligned"><a href="{% url 'website_app:Delete_Objeto_er' item.pk %}"
            class="ui button red">Excluir</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}