api_app/urls.py
from django.urls import path
from .views import JogadorList, Objeto_erList, Objeto_er_mapList, personagens_proximos, me, mochila, job_check_online_users

# *************************************************
from rest_framework import routers

router = routers.DefaultRouter()
router.register('jogador', JogadorList, 'jogador')
router.register('objeto_er', Objeto_erList, 'objeto_er')
router.register('objeto_er_map', Objeto_er_mapList, 'objeto_er_map')

urlpatterns = router.urls
# *************************************************


app_name = "api_app"
urlpatterns += [
    path('personagens/', personagens_proximos, name='personagens_proximos'),
    path('me/', me, name='me'),
    path('mochila/', mochila, name='mochila'),
    path(
        'job_check_online_users/',
        job_check_online_users,
        name='job_check_online_users')
]

core_app/urls.py
from django.urls import path, include, reverse_lazy
from .views import singup_json, singup
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as auth_token
from rest_framework import routers

router = routers.DefaultRouter()

app_name = "core_app"
urlpatterns = [
    path('login/json/', auth_token.obtain_auth_token, name='login_json'),
    path('login/', auth_views.LoginView.as_view(template_name="core_app/login.html",
                                                redirect_authenticated_user=True), name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name="core_app/logout.html"),
        name='logout'),
    path('singup/json/', singup_json, name='singup_json'),
    path('singup/', singup, name='singup'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name="core_app/password_change_form.html",
             success_url=reverse_lazy('core_app:password_change_done')
         ), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="core_app/password_change_done.html"
         ), name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="core_app/password_reset_form.html",
             email_template_name="core_app/password_reset_email.html",
             success_url=reverse_lazy('core_app:password_reset_done')
         ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="core_app/password_reset_done.html"
         ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="core_app/password_reset_confirm.html",
             success_url=reverse_lazy('core_app:password_reset_complete')
         ), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="core_app/password_reset_complete.html"),
         name='password_reset_complete'
         ),
    path('api/', include((router.urls, 'api'), namespace=None)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

khunters/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api_app.urls')),
    path('', include('website_app.urls')),
    path('', include('core_app.urls')),
]

core_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from storages.backends.ftp import FTPStorage
from django.core.files.storage import FileSystemStorage
from rest_framework.authtoken.models import Token
from django.contrib import admin
from django.conf import settings

SERVIDOR_FTP_WEB = FileSystemStorage()

if not settings.DEBUG:
    SERVIDOR_FTP_WEB = FTPStorage()

GENERO = (('M', 'Masculino'), ('F', 'Feminino'))


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True, null=True)
    nome = models.CharField(
        'Nome completo',
        max_length=50,
        null=True,
        blank=True)
    cpf = models.CharField(max_length=50, null=True, blank=True)
    apelido = models.CharField(
        'Como gostaria de ser chamado?',
        max_length=50,
        null=True,
        blank=True)
    foto = models.ImageField(
        "Foto do perfil",
        upload_to='profiles/',
        storage=SERVIDOR_FTP_WEB,
        null=True,
        blank=True)
    sobre = models.TextField("Escreva algo sobre você", null=True, blank=True)
    whatsapp = models.CharField(max_length=50, null=True, blank=True)
    instagram = models.CharField(max_length=100, null=True, blank=True)
    idade = models.IntegerField('Idade', default=18, null=True, blank=True)
    genero = models.CharField(
        'Gênero',
        choices=GENERO,
        max_length=10,
        default='M',
        null=True,
        blank=True)

    def __str__(self):
        if not self.email:
            self.email = self.user.username
            self.save()
        return self.email

    def get_absolute_url(self):
        return ('/profile')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, **kwargs):
    try:
        profile = Profile.objects.get(user=instance)
    except Profile.DoesNotExist:
        profile = Profile(user=instance, email=instance.username)
        profile.save()
    Token.objects.get_or_create(user=instance)


@receiver(post_save, sender=Profile)
def save_user_profile(sender, instance, created, ** kwargs):
    if instance.user.username != instance.email:
        instance.user.username = instance.email
    if instance.user.email != instance.email:
        instance.user.email = instance.email
    instance.user.save()


class ProfileAdmin(admin.ModelAdmin):
    list_display = ('__str__', 'user', 'cpf', 'whatsapp')
    list_display_links = ('__str__',)
    empty_value_display = '--'

core_app/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name']


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', ]

core_app/views.py
from django.shortcuts import render, redirect
from django.core.validators import validate_email
from django.http import JsonResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
import json
from rest_framework.authtoken.models import Token
from django.core.exceptions import ValidationError


@csrf_exempt
def singup_json(request):
    try:
        dados = json.loads(request.body)
        email = dados['email']
        password = dados['password']
    except BaseException:
        email = request.POST.get('email')
        password = request.POST.get('password')

    if not email or not password:
        resultado = {
            "error": "campos obrigatorios faltando",
            "campos": {
                "email": "",
                "password": ""
            }
        }
        return JsonResponse(resultado, safe=False, status=400)

    try:
        validate_email(email)
    except BaseException:
        resultado = {'email': 'E-mail inválido'}
        return JsonResponse(resultado, safe=False, status=400)

    form = UserCreationForm({
        'username': email,
        'password1': password,
        'password2': password
    })
    if form.is_valid():
        form.save()
        user = authenticate(username=email, password=password)
        token = Token.objects.get(user=user)
        return JsonResponse({'token': token.key}, safe=False, status=200)
    errors = json.loads(form.errors.as_json())
    return JsonResponse(errors, safe=False, status=400)


def singup(request):
    form = False
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            try:
                validate_email(username)
            except ValidationError:
                return render(request, 'core_app/singup.html', {
                    'form': form,
                    'erros': {'email': 'Por favor digite um Email valido'},
                }, status=400)
            form.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    if form:
        status = 400
    else:
        status = 200
        form = UserCreationForm()
    return render(request, 'core_app/singup.html',
                  {'form': form}, status=status)

core_app/templates/core_app/form.html
{% extends "html_base.html" %}
{% load i18n static %}
{% block css_page %}
<link rel="stylesheet" href="{% static 'core_app/css/lista.css' %}?{% now 'u' %}">
{% endblock %}
{% block content %}
<div class="ui container segment " style="margin-bottom:5em">
    <form class="ui form formulario " action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        {% if form.errors and not form.non_field_errors %}
        <p class="ui label">
            {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </p>
        {% endif %}

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <p class="ui label">
            {{ error }}
        </p>
        {% endfor %}
        {% endif %}

        {% for field in form %}
        <div class="field">
            <label>{{ field.label_tag }} {{ field.errors }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class="ui fluid button blue" type="submit">Salvar</button>
    </form>
</div>
{% endblock %}

core_app/templates/core_app/login.html
{% extends "html_base.html" %}
{% load i18n static %}

{% block content %}
<div class="ui raised very padded text container segment" style="margin-top:2em">

{% if form.errors and not form.non_field_errors %}
<p class="ui label">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="ui label">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<form action="" method="post" class="ui form">{% csrf_token %}
  <div class="field">
    {{ form.username.errors }}
    <label for="id_username">Email:</label>
    {{ form.username }}
  </div>
  <div class="field">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
  </div>

  <div class="password-reset-link">
    <a href="{% url 'core_app:password_reset' %}">Esqueceu sua senha?</a>
  </div>
  <p/>
  <div class="ui two top attached buttons">
    <button class="ui button positive" type="submit">{% trans 'Log in' %}</button>
    <a class="ui button orange" href="{% url 'core_app:singup' %}" >Criar conta gratuita</a>
  </div>
</form>
</div>
{% endblock %}

core_app/templates/core_app/logout.html
{% extends "html_base.html" %}
{% load i18n %}

{% block content %}
<div class="ui text container  center aligned" style="margin-top:2em">
<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'core_app:login' %}">{% trans 'Log in again' %}</a></p>
</div>
{% endblock %}

core_app/templates/core_app/password_change_done.html
{% extends "html_base.html" %}
{% load i18n %}
{% block content %}
<div class="ui text container  center aligned" style="margin-top:2em">
<a href="/">{% trans 'Home' %}</a>
<p>{% trans 'Your password was changed.' %}</p>
</div>
{% endblock %}

core_app/templates/core_app/password_change_form.html
{% extends "html_base.html" %}
{% load i18n static %}

{% block content %}
<style media="screen">
  .field .label{
    padding:0px !important;
    padding-right:5px !important;
  }
</style>
<div class="ui raised very padded text container segment" style="margin-top:0.5em">

<form class="ui form" method="post">{% csrf_token %}
<div>
{% if form.errors %}
    <p class="ui pointing below red basic label">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
    </p>
{% endif %}


<p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>



<div class="field">
  {% if form.old_password.errors %}
    <div class="ui pointing below red basic label">
      {{ form.old_password.errors }}
    </div>
  {% endif %}
  {{ form.old_password.label_tag }} {{ form.old_password }}
</div>

<div class="field">
  {% if form.new_password1.errors %}
    <div class="ui pointing below red basic label">
      {{ form.new_password1.errors }}
    </div>
  {% endif %}
    {{ form.new_password1.label_tag }} {{ form.new_password1 }}
    {% if form.new_password1.help_text %}
    <div class="">{{ form.new_password1.help_text|safe }}</div>
    {% endif %}
</div>

<div class="field">
  {% if form.new_password2.errors %}
  <div class="ui pointing below red basic label">
    {{ form.new_password2.errors }}
  </div>
  {% endif %}
    {{ form.new_password2.label_tag }} {{ form.new_password2 }}
    {% if form.new_password2.help_text %}
    <div class="">{{ form.new_password2.help_text|safe }}</div>
    {% endif %}
</div>



<div class="field">
    <button type="submit" class="ui button positive">{% trans 'Change my password' %}</button>
</div>

</div>
</form></div>

{% endblock %}

core_app/templates/core_app/password_reset_complete.html
{% extends "html_base.html" %}
{% load i18n %}

{% block content %}
<div class="ui text container  center aligned" style="margin-top:2em">

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a  href="{% url 'core_app:login' %}">{% trans 'Log in' %}</a></p>

</div>
{% endblock %}

core_app/templates/core_app/password_reset_confirm.html
{% extends "html_base.html" %}
{% load i18n static %}

{% block content %}
<div class="ui raised very padded text container segment" style="margin-top:2em">
{% if validlink %}

<p>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<form class="ui form" method="post">{% csrf_token %}

    <div class="field">

        {% if form.new_password1.errors %}
          <div class="ui pointing below red basic label">
            {{ form.new_password1.errors }}
          </div>
        {% endif %}

        <label for="id_new_password1">{% trans 'New password:' %}</label>
        {{ form.new_password1 }}
    </div>
    <div class="field">
        
        {% if form.new_password2.errors %}
          <div class="ui pointing below red basic label">
            {{ form.new_password2.errors }}
          </div>
        {% endif %}
        <label for="id_new_password2">{% trans 'Confirm password:' %}</label>
        {{ form.new_password2 }}
    </div>
    <div class="field">
        <button type="submit" class="ui button positive">{% trans 'Change my password' %}</button>
    </div>

</form>

{% else %}

<p>{% trans "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}</p>

{% endif %}
</div>
{% endblock %}

core_app/templates/core_app/password_reset_done.html
{% extends "html_base.html" %}
{% load i18n %}

{% block content %}
<div class="ui raised very padded text container segment" style="margin-top:2em">
<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

<a href="/" class="ui button positive">{% trans 'Home' %}</a>

</div>
{% endblock %}

core_app/templates/core_app/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'core_app:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

core_app/templates/core_app/password_reset_form.html
{% extends "html_base.html" %}
{% load i18n static %}

{% block content %}
<div class="ui raised very padded text container segment" style="margin-top:0.5em">
<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post" class="ui form">{% csrf_token %}

    <div class="field">
        {{ form.email.errors }}
        <label for="id_email">{% trans 'Email address:' %}</label>
        {{ form.email }}
    </div>
    <div class="field">
        <button type="submit" class="ui button positive">{% trans 'Reset my password' %}</button>
    </div>

</form>
</div>
{% endblock %}

core_app/templates/core_app/singup.html
{% extends "html_base.html" %}
{% load i18n static %}

{% block content %}

<div class="ui raised very padded text container segment" style="margin-top:2em">
  <div class="ui center aligned header">Cadastre-se para participar!</div>

  {% if form.errors and not form.non_field_errors %}
  <p class="ui label">
    {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
  </p>
  {% endif %}

  {% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
  <p class="ui label">
    {{ error }}
  </p>
  {% endfor %}
  {% endif %}

  <form action="" method="post" class="ui form">{% csrf_token %}
    <div class="field">
      {{ form.username.errors }}
      <b>Email:</b>
      <p>{{erros.email}}</p>
      {{ form.username }}
    </div>
    <div class="field">
      {{ form.password1.errors }}
      {{ form.password1.label_tag }} {{ form.password1 }}
    </div>
    <div class="field">
      {{ form.password2.errors }}
      {{ form.password2.label_tag }} {{ form.password2 }}
    </div>

    <div class="field">
      <label>&nbsp;</label>
      <button class="ui fluid button positive" type="submit">
        Cadastrar
      </button>
    </div>
    <p class="ui small header center aligned">
      <a href="/" class="ui ">voltar para o início</a>
    </p>
  </form>
</div>
{% endblock %}