api_app/urls.py
from django.urls import path
from .views import JogadorList, Objeto_erList, Objeto_er_mapList, personagens_proximos, me, mochila, job_check_online_users

# *************************************************
from rest_framework import routers

router = routers.DefaultRouter()
router.register('jogador', JogadorList, 'jogador')
router.register('objeto_er', Objeto_erList, 'objeto_er')
router.register('objeto_er_map', Objeto_er_mapList, 'objeto_er_map')

urlpatterns = router.urls
# *************************************************


app_name = "api_app"
urlpatterns += [
    path('personagens/', personagens_proximos, name='personagens_proximos'),
    path('me/', me, name='me'),
    path('mochila/', mochila, name='mochila'),
    path(
        'job_check_online_users/',
        job_check_online_users,
        name='job_check_online_users')
]

core_app/urls.py
from django.urls import path, include, reverse_lazy
from .views import singup_json, singup
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views as auth_token
from rest_framework import routers

router = routers.DefaultRouter()

app_name = "core_app"
urlpatterns = [
    path('login/json/', auth_token.obtain_auth_token, name='login_json'),
    path('login/', auth_views.LoginView.as_view(template_name="core_app/login.html",
                                                redirect_authenticated_user=True), name='login'),
    path(
        'logout/',
        auth_views.LogoutView.as_view(
            template_name="core_app/logout.html"),
        name='logout'),
    path('singup/json/', singup_json, name='singup_json'),
    path('singup/', singup, name='singup'),
    path('password_change/',
         auth_views.PasswordChangeView.as_view(
             template_name="core_app/password_change_form.html",
             success_url=reverse_lazy('core_app:password_change_done')
         ), name='password_change'),
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(
             template_name="core_app/password_change_done.html"
         ), name='password_change_done'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
             template_name="core_app/password_reset_form.html",
             email_template_name="core_app/password_reset_email.html",
             success_url=reverse_lazy('core_app:password_reset_done')
         ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name="core_app/password_reset_done.html"
         ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name="core_app/password_reset_confirm.html",
             success_url=reverse_lazy('core_app:password_reset_complete')
         ), name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name="core_app/password_reset_complete.html"),
         name='password_reset_complete'
         ),
    path('api/', include((router.urls, 'api'), namespace=None)),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

khunters/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api_app.urls')),
    path('', include('website_app.urls')),
    path('', include('core_app.urls')),
]

website_app/urls.py
from django.urls import path
from website_app import views

app_name = "website_app"
urlpatterns = [
    path('', views.index, name='Index'),
    path('jogadores/', views.Jogadores, name='Jogadores'),

    path(
        'jogadores/add/',
        views.JogadorCreate.as_view(),
        name='Add_Jogador'),

    path(
        'jogadores/up/<int:pk>/',
        views.JogadorUpdateView.as_view(),
        name='Update_Jogador'),

    path(
        'jogadores/del/<int:pk>/',
        views.JogadorDeleteView.as_view(),
        name='Delete_Jogador'),

    path(
        'objeto_ers/',
        views.Objeto_ers,
        name='Objeto_ers'),

    path(
        'objeto_ers/add/',
        views.Objeto_erCreate.as_view(),
        name='Add_Objeto_er'),

    path(
        'objeto_ers/up/<int:pk>/',
        views.Objeto_erUpdateView.as_view(),
        name='Update_Objeto_er'),

    path(
        'objeto_ers/del/<int:pk>/',
        views.Objeto_erDeleteView.as_view(),
        name='Delete_Objeto_er'),

    path(
        'objeto_er_maps/',
        views.Objeto_er_maps,
        name='Objeto_er_maps'),

    path(
        'objeto_er_maps/add/',
        views.Objeto_er_mapCreate.as_view(),
        name='Add_Objeto_er_map'),

    path(
        'objeto_er_maps/up/<int:pk>/',
        views.Objeto_er_mapUpdateView.as_view(),
        name='Update_Objeto_er_map'),

    path(
        'objeto_er_maps/del/<int:pk>/',
        views.Objeto_er_mapDeleteView.as_view(),
        name='Delete_Objeto_er_map'),
]

website_app/models.py
from .models_includes import NIVEL_DE_AUTISMO, AREA_DE_CONHECIMENTO, DIFICULDADE, TIPO_DE_ARQUIVO, IDIOMA
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from storages.backends.ftp import FTPStorage
SERVIDOR_FTP_WEB = FTPStorage()


class Jogador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.CharField(max_length=255, null=True, blank=True)
    online = models.BooleanField(default=False)
    latitude = models.CharField(
        'Latitude', max_length=255, null=True, blank=True)
    longitude = models.CharField(
        'Longitude', max_length=255, null=True, blank=True)
    animacao = models.CharField(max_length=255, null=True, blank=True)
    nivel_de_autismo = models.CharField(
        'Nível de Autismo', choices=NIVEL_DE_AUTISMO, max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('website_app:Jogadores')


@receiver(post_save, sender=User)
def save_user_jogador(sender, instance, **kwargs):
    Jogador.objects.get_or_create(user=instance)


class Personagem(models.Model):
    descricao = models.CharField("Descrição", max_length=100)
    prefab = models.CharField(max_length=50)
    tamanho = models.CharField("Tamanho: ", max_length=10, default="1.0")

    def __str__(self):
        return str(self.descricao)

    class Meta:
        ordering = ('descricao',)


class Objeto_er(models.Model):
    personagem = models.ForeignKey(
        Personagem, on_delete=models.PROTECT, null=True, blank=True)
    titulo = models.CharField(
        'Titulo do objeto de aprendizagem', max_length=255, null=True, blank=True)
    sub_titulo = models.CharField(
        'Sub titulo', max_length=255, null=True, blank=True)
    descricao = models.CharField(
        'Descrição', max_length=255, null=True, blank=True)
    area_de_conhecimento = models.CharField(
        'Área de Conhecimento', choices=AREA_DE_CONHECIMENTO, max_length=50, null=True, blank=True)
    dificuldade = models.CharField(
        'Nível de dificuldade', choices=DIFICULDADE, max_length=20, null=True, blank=True)
    tipo_de_arquivo = models.CharField(
        'Tipo de arquivo', max_length=10, choices=TIPO_DE_ARQUIVO, null=True, blank=True)
    # Text
    autor = models.ForeignKey(
        User, on_delete=models.PROTECT, null=True, blank=True)
    texto = models.CharField('Texto', max_length=255, null=True, blank=True)
    idioma = models.CharField('Idioma', max_length=10,
                              choices=IDIOMA, null=True, blank=True)
    # Imagem
    arquivo_1 = models.FileField(
        'Arquivo Principal', upload_to='arquivos/objeto_er/', null=True, blank=True, storage=SERVIDOR_FTP_WEB)
    arquivo_2 = models.FileField(
        'Arquivo Secundário:', upload_to='arquivos/objeto_er/', null=True, blank=True, storage=SERVIDOR_FTP_WEB)
    # Audio, Video
    duracao = models.IntegerField(
        "Duração em Minutos", default=0, null=True, blank=True)

    def __str__(self):
        return str(self.personagem) + " - " + str(self.titulo)

    def get_absolute_url(self):
        return reverse('website_app:Objeto_ers')


class Objeto_er_map(models.Model):
    latitude = models.CharField(
        'Latitude', max_length=255, null=True, blank=True)
    longitude = models.CharField(
        'Longitude', max_length=255, null=True, blank=True)
    objeto_er = models.ForeignKey(Objeto_er, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.objeto_er)

    def get_absolute_url(self):
        return reverse('website_app:Objeto_er_maps')


class Captura(models.Model):
    latitude = models.CharField(max_length=255, null=True, blank=True)
    longitude = models.CharField(max_length=255, null=True, blank=True)
    objeto_er = models.ForeignKey(Objeto_er, on_delete=models.CASCADE)
    data = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.objeto_er)

    def get_absolute_url(self):
        return reverse('website_app:index')


class Mochila(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    personagem = models.ForeignKey(
        Personagem, on_delete=models.PROTECT, null=True, blank=True)
    quantidade = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return str(self.user) + ' - ' + str(self.personagem)

website_app/views.py
from django.shortcuts import render
from django.views.generic.edit import DeleteView, CreateView, UpdateView
from .models import Personagem, Objeto_er, Objeto_er_map, Jogador
from django.urls import reverse_lazy
from django.contrib.auth.decorators import user_passes_test


def index(request):
    contexto = {}
    Personagem.objects.get_or_create(
        descricao="Moeda Dourada", prefab="MoedaDourada")
    Objeto_er.objects.get_or_create(personagem=Personagem.objects.first())
    return render(request, 'website_app/index.html', contexto)


def login_staff_required(function=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_staff,
        login_url="/",
        redirect_field_name=None
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


def Jogadores(request):
    jogadores = Jogador.objects.all()
    lista = []
    for i in jogadores:
        try:
            lista.append([float(i.longitude.replace(',', '.')),
                          float(i.latitude.replace(',', '.'))])
        except BaseException:
            pass
    contexto = {
        "jogadores": Jogador.objects.all(),
        "lista_js": lista
    }
    return render(request, 'website_app/jogadores.html', contexto)


class JogadorCreate(CreateView):
    model = Jogador
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


class JogadorUpdateView(UpdateView):
    model = Jogador
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


class JogadorDeleteView(DeleteView):
    model = Jogador
    success_url = reverse_lazy('website_app:Jogadores')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_jogador'] = "active"
        return context


def Objeto_ers(request):
    contexto = {
        "lista": Objeto_er.objects.all(),
    }
    contexto["item_active_objeto_er"] = "active"
    return render(request, 'website_app/objeto_ers.html', contexto)


class Objeto_erCreate(CreateView):
    model = Objeto_er
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


class Objeto_erUpdateView(UpdateView):
    model = Objeto_er
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


class Objeto_erDeleteView(DeleteView):
    model = Objeto_er
    success_url = reverse_lazy('website_app:Objeto_ers')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er'] = "active"
        return context


# ---------- Objeto_er_maps ---------------------------------------------------


def Objeto_er_maps(request):
    objeto_er_maps = Objeto_er_map.objects.all()
    lista = []
    for i in objeto_er_maps:
        lista.append(
            [
                float(i.longitude.replace(',', '.')),
                float(i.latitude.replace(',', '.'))
            ]
        )
    contexto = {
        "lista": Objeto_er_map.objects.all(),
        "lista_js": lista
    }
    contexto["item_active_objeto_er_map"] = "active"
    # return HttpResponse(lista)
    return render(request, 'website_app/objeto_er_maps.html', contexto)


class Objeto_er_mapCreate(CreateView):
    model = Objeto_er_map
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context


class Objeto_er_mapUpdateView(UpdateView):
    model = Objeto_er_map
    fields = '__all__'
    template_name = 'website_app/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context


class Objeto_er_mapDeleteView(DeleteView):
    model = Objeto_er_map
    success_url = reverse_lazy('website_app:Objeto_er_maps')
    template_name = 'website_app/confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item_active_objeto_er_map'] = "active"
        return context

website_app/templates/website_app/includes/base.html
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  {% load static %}
  {% include 'website_app/includes/cabecalho.html' %}
</head>
<body>
  {% include 'website_app/includes/menus.html' %}
  <!-- Page Contents -->
  <div class="pusher">
    {% include 'website_app/includes/menu_horizontal.html' %}
    {% block content %}
    {% endblock %}
    {% include 'website_app/includes/rodape.html' %}
  </div>

</body>

</html>

website_app/templates/website_app/includes/cabecalho.html
{% load static %}
<title>Khunters-Admin</title>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta http-equiv="Cache-control" content="no-cache">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" charset="utf-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" charset="utf-8"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
<script charset="utf-8">
  $(document)
  .ready(function() {
    // fix menu when passed
    $('.masthead')
    .visibility({
      once: false,
      onBottomPassed: function() {
        $('.fixed.menu').transition('fade in');
      },
      onBottomPassedReverse: function() {
        $('.fixed.menu').transition('fade out');
      }
    });
    // create sidebar and attach to menu open
    $('.ui.sidebar').sidebar('attach events', '.toc.item');
    $('.ui.checkbox').checkbox();
    // $('.special.card').dimmer({on: 'hover'});
    $( "#id_categoria" ).addClass("ui dropdown");
    $( "#id_tag" ).addClass("ui dropdown");
    $('.ui.dropdown').dropdown();
  });
</script>
<style media="screen">
  .hidden.menu {
    display: none;
  }
  .barra .menu .item_menu_horizontal{
    margin: 0 auto !important;
  }
  .menu .toc.item {
    display: none !important;
    margin-left: 0px !important;
  }
  @media only screen and (max-width: 700px) {
    .logo{
      margin-top:4em
    }
    .ui.fixed.menu {
      display: none !important;
    }
    .barra{
      background: #000000 !important;
      position: fixed;
      z-index: 101;
      width: 100%;
      top: 0;
    }
    .barra .menu{
      padding: 0px !important;
    }
    .item_menu_horizontal{
      display: none !important;
    }
    .secondary.pointing.menu .item,
    .secondary.pointing.menu .menu {
      display: none;
    }
    .menu .toc.item {
      display: block !important;
    }
  }
</style>

website_app/templates/website_app/includes/items.html
<a class="item" href="{% url 'website_app:Index' %}">Inicio</a>
{% if user.is_staff %}
<a class="item {{item_active_jogador}}" href="{% url 'website_app:Jogadores' %}">Jogadores</a>
<a class="item {{item_active_objeto_er}}" href="{% url 'website_app:Objeto_ers' %}">Objetos de Aprendizagem</a>
<a class="item {{item_active_objeto_er_map}}" href="{% url 'website_app:Objeto_er_maps' %}">Objetos no Mapa</a>
<a class="item">Estatísticas</a>
{% endif %}
{% if user.is_authenticated %}
<a class="item " href="{% url 'core_app:password_change' %}">Mudar senha</a>
<a class="item " href="">Meu perfil</a>
<a class="right menu item" href="{% url 'core_app:logout' %}">Sair</a>
{% else %}
<a class="right menu item" href="{% url 'core_app:login' %}">Entrar</a>
{% endif %}

website_app/templates/website_app/includes/menu_horizontal.html
{% load static %}
<div class="ui vertical masthead center aligned container">
  <a href="/"><img class="ui image fluid logo" src="{% static 'logo.png' %}" alt="Logo"></a>
</div>
<div class="barra">
  <div class="ui container item_menu_horizontal ">
    <div class="ui menu">
      {% include 'website_app/includes/items.html' %}
    </div>
  </div>
  <div class="ui container  ">
    <div class="ui large secondary inverted  menu">
      <a class="toc item">
        <i class="ui icon big bars white"></i>
      </a>
      <a class="item item_menu_horizontal" href="/">Home</a>
      <!--  Fim Pesquisar -->
    </div><!--  Fim Menu -->
  </div><!--  Fim Container -->
</div><!--  Fim Barra -->

website_app/templates/website_app/includes/menus.html
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    {% include 'website_app/includes/items.html' %}
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  {% include 'website_app/includes/items.html' %}
</div>

website_app/templates/website_app/includes/rodape.html
{% load static %}
<div class="ui vertical footer segment" style="margin-top: 10em;padding:1em">
  <div class="ui section divider"></div>
  <div class="ui center aligned container">
    <div class="ui stackable inverted grid" >
      <div class="five wide column">
        <h3 class="ui header">Contato</h3>
        <div class="ui list">
          <div class="item">miltonmendes@ufersa.edu.br</div>
          <div class="item">tieldantas@gmail.com</div>
          <div class="item">naylsonfsa@gmail.com</div>
        </div>
      </div>

      <div class="six wide column">
        <img class="ui image centered" style="padding-top:1em" src="{% static 'khunters/logoufersa.png' %}" alt="ufersa">
      </div>

      <div class="five wide column">
        <img class="ui small image centered" src="{% static 'khunters/overloadlab.png' %}" alt="overloadlab">
      </div>

    </div>
    <div class="ui section divider"></div>
    <div class="ui horizontal">
      <div class="item">Copyrigth {% now 'yy' %} Todos os direitos reservados</div>
      <a href="/admin" class="item">admin</a>
    </div>
  </div>
</div>